export const NICKNAME_SET = "NICKNAME_SET";
export const MESSAGE_REMOVED = "MESSAGE_REMOVED";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const MESSAGE_UPDATED = "MESSAGE_UPDATED";
export const USER_STARTED_TYPING = "USER_STARTED_TYPING";
export const USER_STOPPED_TYPING = "USER_STOPPED_TYPING";