export const NICKNAME_SET = "NICKNAME_SET";
export const MESSAGE_REMOVED = "MESSAGE_REMOVED";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const THINK_MESSAGE_RECEIVED = "THINK_MESSAGE_RECEIVED";